WebUI/Models/Member/MemberViewModel.cs
using System;
using Core.Entities.Concrete;
using Entities.Dtos;

namespace WebUI.Models.Member
{
    public class MemberViewModel
    {
        public MemberViewModel()
        {
        }

        public User User { get; set; }
        public string CurrentView { get; set; }
        public UserForChangePasswordDto userForChangePasswordDto { get; set; }
    }
}

WebUI/Models/Member/RoleAssignViewModel.cs
using System;
using System.Collections.Generic;
using Core.Entities.Concrete;

namespace WebUI.Models.Member
{
    public class RoleAssignViewModel
    {
        public RoleAssignViewModel()
        {
        }

        public List<Role> Roles { get; set; }
        public string UserId { get; set; }
    }
}

WebUI/Models/Member/RoleViewModel.cs
using System;
using System.Collections.Generic;
using Core.Entities.Concrete;

namespace WebUI.Models.Member
{
    public class RoleViewModel
    {
        public RoleViewModel()
        {
        }

        public Role Role { get; set; }
        public List<Role> Roles { get; set; }
    }
}

WebUI/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Core.Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebUI.Models.Member;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebUI.Controllers
{
    [Authorize]
    public class MemberController : Controller
    {

        private IUserService _userService;

        public MemberController(IUserService userService)
        {
            _userService = userService;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var user = _userService.FindByName(User.Identity.Name);
            var model = new MemberViewModel { CurrentView = "Index" ,User=user};
            return View(model);
        }

        public IActionResult PasswordChange()
        {
            var model = new MemberViewModel { CurrentView = "PasswordChange" };
            return View(model);
        }

        [HttpPost]
        public IActionResult PasswordChange(UserForChangePasswordDto userForChangePasswordDto)
        {

            var model = new MemberViewModel { CurrentView = "PasswordChange", userForChangePasswordDto=userForChangePasswordDto };
            
            if (!ModelState.IsValid)
            {
                
                return View(model);
            }

           

            var result = _userService.ChangePassword(User.Identity.Name, userForChangePasswordDto);

            if (result.Success)
            {
                TempData.Add("message", "Password has changed");
                return View(model);
            }

            ModelState.AddModelError("", result.Message);

            
            return View(model);
        }

        public IActionResult UpdateUserInfo()
        {
            var model = new MemberViewModel { CurrentView = "UpdateUserInfo" };
            var user = _userService.FindByName(User.Identity.Name);
            model.User = user;
            return View(model);
        }

        [HttpPost]
        public IActionResult UpdateUserInfo(User user,IFormFile userPicture)
        {
            var model = new MemberViewModel { CurrentView = "UpdateUserInfo" };
            model.User = user;
            if (!ModelState.IsValid)
            {

                return View(model);
            }

            if (userPicture!=null && userPicture.Length>0)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(userPicture.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/UserPicture", fileName);
                using (var stream = new FileStream(path,FileMode.Create))
                {
                    userPicture.CopyTo(stream);
                    user.Picture = "/images/UserPicture/" + fileName;
                }
            }

            var result = _userService.UpdateUser(user);

            if (result.Success)
            {
                TempData.Add("message", "User has updated");
                return View(model);
            }

            ModelState.AddModelError("", result.Message);



            return View(model);
        }

        public void LogOut()
        {
            _userService.SignOut();
        }

       
    }
}

WebUI/ViewComponents/MemberMenuViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace WebUI.ViewComponents
{
    public class MemberMenuViewComponent : ViewComponent
    {
        public MemberMenuViewComponent()
        {
        }

        public ViewViewComponentResult Invoke()
        {
            return View();
        }

    }
}

WebUI/Views/Member/Index.cshtml
@model WebUI.Models.Member.MemberViewModel

@{
    ViewData["Title"] = "Member Page";
}

<div class="row" style="margin-top:10px;">
    <div class="col-md-3">
        @await Component.InvokeAsync("MemberMenu")
    </div>
    <div class="col-md-9">

        <img style="height: 120px; width: 80px; display: block;" src="@(Model.User.Picture==null?Href("~/images/UserPicture/simpleuser.png"):Model.User.Picture) " alt="User image">

        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered table-striped" style="margin-top:10px;">
                    <tr>
                        <th>User Name</th>
                        <td>@Model.User.UserName</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>@Model.User.Email</td>
                    </tr>
                    <tr>
                        <th>Phone Number</th>
                        <td>@Model.User.PhoneNumber</td>
                    </tr>
                    <tr>
                        <th>City</th>
                        <td>@Model.User.City</td>
                    </tr>
                    <tr>
                        <th>Adress</th>
                        <td>@Model.User.Adresse</td>
                    </tr>
                    <tr>
                        <th>Photo</th>
                        <td>@Model.User.Picture</td>
                    </tr>
                    <tr>
                        <th>Birthday</th>
                      
                        <td>@Model.User.Birthday?.ToShortDateString()</td>
                    </tr>
                    <tr>
                        <th>Gender</th>
                        @if (Model.User.Gender == 1)
                        {<td>Male</td>}
                        else if (Model.User.Gender == 2)
                        { <td>Female</td>}
                        else {<td>-</td> }
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>

WebUI/Views/Member/Logout.cshtml
@model WebUI.Models.Member.MemberViewModel

@{
    ViewData["Title"] = "Member Page";
}

<div class="row" style="margin-top:10px;">
    <div class="col-md-3">
        @await Component.InvokeAsync("MemberMenu")
    </div>
    
</div>

WebUI/Views/Member/PasswordChange.cshtml
@model WebUI.Models.Member.MemberViewModel

@{
    ViewData["Title"] = "Password Change Page";
}

<div class="row" style="margin-top:10px;">
    <div class="col-md-3">
        @await Component.InvokeAsync("MemberMenu")
    </div>
    <div class="col-md-9">
        <div class="container">
            <div id="loginbox" style="margin-top:10px;" class="mainbox col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Change Password</div>
                    </div>
                    <div style="padding-top:30px" class="panel-body">
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                        <form asp-controller="Member" asp-action="PasswordChange" method="post" class="form-horizontal" role="form">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input asp-for="userForChangePasswordDto.PasswordOld" class="form-control" placeholder="Password Old">

                            </div>

                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input asp-for="userForChangePasswordDto.PasswordNew" class="form-control" placeholder="Password New">

                            </div>

                            <div style="margin-bottom: 25px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                <input asp-for="userForChangePasswordDto.ConfirmPassword" class="form-control" placeholder="Confirm Password">

                            </div>





                            <div style="margin-top:10px" class="form-group">
                                <!-- Button -->
                                <div class="col-sm-12 controls">
                                    <input type="submit" class="btn btn-success" value="Change">
                                </div>
                            </div>


                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebUI/Views/Member/UpdateUserInfo.cshtml
@model WebUI.Models.Member.MemberViewModel

@{
    ViewData["Title"] = "Member Page";
}

<div class="row" style="margin-top:10px;">
    <div class="col-md-3">
        @await Component.InvokeAsync("MemberMenu")
    </div>
    <div class="col-md-9">
        <div class="container">
            <div id="loginbox" style="margin-top:10px;" class="mainbox col-md-6">
                <div class="panel panel-info">

                    <div style="padding-top:10px" class="panel-body">
                        <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>

                        <form asp-controller="Member" asp-action="UpdateUserInfo" method="post" class="form-horizontal" role="form" enctype="multipart/form-data">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div style="margin-top: 10px" class="input-group">
                                <label asp-for="User.UserName">User Name</label>
                            </div>
                            <div style="margin-top: 5px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                <input asp-for="User.UserName" class="form-control" placeholder="username">
                                @*<span asp-validation-for="userForRegisterDto.Email" class="text-danger"></span>*@
                            </div>

                            <div style="margin-top: 20px" class="input-group">
                                <label asp-for="User.PhoneNumber"></label>
                            </div>
                            <div style="margin-top: 5px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                                <input asp-for="User.PhoneNumber" class="form-control" placeholder="phone number">
                                @*<span asp-validation-for="userForRegisterDto.PhoneNumber" class="text-danger"></span>*@
                            </div>
                            <div style="margin-top: 20px" class="input-group">
                                <label asp-for="User.Birthday"></label>
                            </div>
                            <div style="margin-top: 5px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                                <input asp-for="User.Birthday" type="date" class="form-control" placeholder="Birthday">
                                @*<span asp-validation-for="userForRegisterDto.PhoneNumber" class="text-danger"></span>*@
                            </div>

                            <div style="margin-top: 20px" class="input-group">
                                <label asp-for="User.Adresse"></label>
                            </div>
                            <div style="margin-top: 5px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                                <input asp-for="User.Adresse" class="form-control" placeholder="Adress">
                                @*<span asp-validation-for="userForRegisterDto.PhoneNumber" class="text-danger"></span>*@
                            </div>

                            <div style="margin-top: 20px" class="input-group">
                                <label asp-for="User.Gender"></label>
                            </div>
                            <div style="margin-top: 5px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                                @*<input asp-for="User.Gender" class="form-control" placeholder="Gender">*@

                                <select class="form-control" asp-for="User.Gender">
                                    <option value="0">
                                    </option>
                                    <option value="1">Male</option>
                                    <option value="2">FeMale</option>
                                </select>

                                @*<span asp-validation-for="userForRegisterDto.PhoneNumber" class="text-danger"></span>*@
                            </div>
                            <div style="margin-top: 20px" class="input-group">
                                <label asp-for="User.Picture"></label>
                            </div>
                            <div style="margin-top: 5px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                                <input name="userPicture" type="file" class="form-control-file" placeholder="Picture">
                                @*<span asp-validation-for="userForRegisterDto.PhoneNumber" class="text-danger"></span>*@
                            </div>
                            <div style="margin-top: 20px" class="input-group">
                                <label asp-for="User.City"></label>
                            </div>
                            <div style="margin-top: 5px" class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                                <input asp-for="User.City" class="form-control" placeholder="City">
                                @*<span asp-validation-for="userForRegisterDto.PhoneNumber" class="text-danger"></span>*@
                            </div>
                            <input asp-for="User.Email" type="hidden" />
                            <input asp-for="User.Picture" type="hidden" />
                            <div style="margin-top:10px" class="form-group">
                                <!-- Button -->
                                <div class="col-sm-12 controls">
                                    <input type="submit" class="btn btn-success" value="Update">
                                </div>
                            </div>


                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>