WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Core.Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebUI.Models.Member;
using WebUI.Models.UserModel;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebUI.Controllers
{
    [Authorize(Roles="Admin,Editor")]
    public class AdminController : Controller
    {

        private IUserService _userService;

        public AdminController(IUserService userService)
        {
            _userService = userService;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var users = _userService.GetUsers();

            var userListViewModel = new UserListViewModel { Users = users };
            return View(userListViewModel);
        }

        public IActionResult Users()
        {

            var users = _userService.GetUsers();

            var userListViewModel = new UserListViewModel { Users = users };
            return View(userListViewModel);

        }

        public IActionResult RoleCreate()
        {
            var result = _userService.GetRoles();

            RoleViewModel roleViewModel = new RoleViewModel { Roles = result };

            return View(roleViewModel);
        }

        [HttpPost]
        public IActionResult RoleCreate(RoleViewModel roleViewModel)
        {

            if (!ModelState.IsValid)
            {
                return View(roleViewModel);
            }

            TempData.Remove("message");
            var result = _userService.RoleCreate(roleViewModel.Role);
            if (result.Success)
            {
                TempData.Add("message", "Role Added");
                return RedirectToAction("RoleCreate");
            }

            ModelState.AddModelError("", result.Message);

            return View(roleViewModel);
        }


        public IActionResult RoleDelete(string roleId)
        {
            var result = _userService.RoleDelete(roleId);
            if (result.Success)
            {
                TempData.Add("message", "Role deleted");
                return RedirectToAction("RoleCreate");
            }

            ModelState.AddModelError("", result.Message);

            return RedirectToAction("RoleCreate");
        }

        public IActionResult RoleAssign(string userId)
        {
            List<Role> roles = _userService.GetRoles();
            List<string> userRoles = _userService.GetUserRoles(userId);
            if (userRoles != null)
            {
                foreach (var role in roles)
                {
                    if (userRoles.Contains(role.RoleName))
                    {
                        role.IsChecked = true;
                    }
                }
            }

            RoleAssignViewModel roleAssignViewModel = new RoleAssignViewModel { UserId = userId, Roles = roles };

            return View(roleAssignViewModel);
        }

        [HttpPost]
        public IActionResult RoleAssign(RoleAssignViewModel roleAssignViewModel)
        {
            var result = _userService.AddRolesToUser(roleAssignViewModel.Roles, roleAssignViewModel.UserId);
            if (result.Success)
            {
                TempData.Add("message", "Roles Update");
                return RedirectToAction("RoleAssign",new {userId = roleAssignViewModel.UserId });
            }

            ModelState.AddModelError("", result.Message);

            return View(roleAssignViewModel);
        }
    }
}

WebUI/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Business.Abstract;
using Core.Entities.Concrete;
using Entities.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebUI.Models.Member;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebUI.Controllers
{
    [Authorize]
    public class MemberController : Controller
    {

        private IUserService _userService;

        public MemberController(IUserService userService)
        {
            _userService = userService;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            var user = _userService.FindByName(User.Identity.Name);
            var model = new MemberViewModel { CurrentView = "Index" ,User=user};
            return View(model);
        }

        public IActionResult PasswordChange()
        {
            var model = new MemberViewModel { CurrentView = "PasswordChange" };
            return View(model);
        }

        [HttpPost]
        public IActionResult PasswordChange(UserForChangePasswordDto userForChangePasswordDto)
        {

            var model = new MemberViewModel { CurrentView = "PasswordChange", userForChangePasswordDto=userForChangePasswordDto };
            
            if (!ModelState.IsValid)
            {
                
                return View(model);
            }

           

            var result = _userService.ChangePassword(User.Identity.Name, userForChangePasswordDto);

            if (result.Success)
            {
                TempData.Add("message", "Password has changed");
                return View(model);
            }

            ModelState.AddModelError("", result.Message);

            
            return View(model);
        }

        public IActionResult UpdateUserInfo()
        {
            var model = new MemberViewModel { CurrentView = "UpdateUserInfo" };
            var user = _userService.FindByName(User.Identity.Name);
            model.User = user;
            return View(model);
        }

        [HttpPost]
        public IActionResult UpdateUserInfo(User user,IFormFile userPicture)
        {
            var model = new MemberViewModel { CurrentView = "UpdateUserInfo" };
            model.User = user;
            if (!ModelState.IsValid)
            {

                return View(model);
            }

            if (userPicture!=null && userPicture.Length>0)
            {
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(userPicture.FileName);
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images/UserPicture", fileName);
                using (var stream = new FileStream(path,FileMode.Create))
                {
                    userPicture.CopyTo(stream);
                    user.Picture = "/images/UserPicture/" + fileName;
                }
            }

            var result = _userService.UpdateUser(user);

            if (result.Success)
            {
                TempData.Add("message", "User has updated");
                return View(model);
            }

            ModelState.AddModelError("", result.Message);



            return View(model);
        }

        public void LogOut()
        {
            _userService.SignOut();
        }

       
    }
}

WebUI/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js" rel="stylesheet" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <style>
        /*
*
* ==========================================
* CUSTOM UTIL CLASSES
* ==========================================
*
*/

.vertical-nav {
  min-width: 17rem;
  width: 17rem;
  height: 100vh;
  position: fixed;
  top: 0;
  left: 0;
  box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1);
  transition: all 0.4s;
}

.page-content {
  width: calc(100% - 17rem);
  margin-left: 17rem;
  transition: all 0.4s;
}

/* for toggle behavior */

#sidebar.active {
  margin-left: -17rem;
}

#content.active {
  width: 100%;
  margin: 0;
}

@*@media (max-width: 768px) {
  #sidebar {
    margin-left: -17rem;
  }*@
  #sidebar.active {
    margin-left: 0;
  }
  #content {
    width: 100%;
    margin: 0;
  }
  #content.active {
    margin-left: 17rem;
    width: calc(100% - 17rem);
  }
}

/*
*
* ==========================================
* FOR DEMO PURPOSE
* ==========================================
*
*/

body {
  background: #599fd9;
  background: -webkit-linear-gradient(to right, #599fd9, #c2e59c);
  background: linear-gradient(to right, #599fd9, #c2e59c);
  min-height: 100vh;
  overflow-x: hidden;
}

.separator {
  margin: 3rem 0;
  border-bottom: 1px dashed #fff;
}

.text-uppercase {
  letter-spacing: 0.1em;
}

.text-gray {
  color: #aaa;
}
    </style>

    <script type="text/javascript">$(function () {
            // Sidebar toggle behavior
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
            });
        });</script>
</head>
<body>
    <!-- Vertical navbar -->
    <div class="vertical-nav bg-white" id="sidebar">
        <div class="py-4 px-3 mb-4 bg-light">
            <div class="media d-flex align-items-center">
                <img src="https://res.cloudinary.com/mhmd/image/upload/v1557368579/logo_iqjuay.png" alt="..." width="65" class="mr-3 rounded-circle img-thumbnail shadow-sm">
                <div class="media-body">
                    <h4 class="m-0">Admin Panel</h4>
                    <p class="font-weight-light text-muted mb-0"></p>
                </div>
            </div>
        </div>

        <p class="text-gray font-weight-bold text-uppercase px-3 small pb-4 mb-0">Main</p>

        <ul class="nav flex-column bg-white mb-0">
            <li class="nav-item">
                <a href="@Url.Action("index","Admin")" class="nav-link text-dark font-italic bg-light">
                    <i class="fa fa-th-large mr-3 text-primary fa-fw"></i>
                    Home
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("users","Admin")" class="nav-link text-dark font-italic">
                    <i class="fa fa-address-card mr-3 text-primary fa-fw"></i>
                    Users
                </a>
            </li>
            <li class="nav-item">
                <a href="@Url.Action("RoleCreate","Admin")" class="nav-link text-dark font-italic">
                    <i class="fa fa-cubes mr-3 text-primary fa-fw"></i>
                    Roles
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link text-dark font-italic">
                    <i class="fa fa-picture-o mr-3 text-primary fa-fw"></i>
                    Gallery
                </a>
            </li>
        </ul>

        <p class="text-gray font-weight-bold text-uppercase px-3 small py-4 mb-0">Charts</p>

        <ul class="nav flex-column bg-white mb-0">
            <li class="nav-item">
                <a href="#" class="nav-link text-dark font-italic">
                    <i class="fa fa-area-chart mr-3 text-primary fa-fw"></i>
                    Area charts
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link text-dark font-italic">
                    <i class="fa fa-bar-chart mr-3 text-primary fa-fw"></i>
                    Bar charts
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link text-dark font-italic">
                    <i class="fa fa-pie-chart mr-3 text-primary fa-fw"></i>
                    Pie charts
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link text-dark font-italic">
                    <i class="fa fa-line-chart mr-3 text-primary fa-fw"></i>
                    Line charts
                </a>
            </li>
        </ul>
    </div>
    <!-- End vertical navbar -->
    <!-- Page content holder -->
    <div class="page-content p-5" id="content">
        <!-- Toggle button -->
        <div class="container">
            @if (TempData["message"] != null)
            {

                <div class="alert alert-info" style="text-align:center;">

                    <strong>@TempData["message"]</strong>
                </div>
            }
        </div>

        @RenderBody()

    </div>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</body>
</html>

WebUI/Views/Shared/_Alerts.cshtml
@{

    var alerts = TempData.ContainsKey(Alert.TempDataKey)

    ? (List<Alert>)TempData[Alert.TempDataKey]

    : new List<Alert>();

    foreach (var alert in alerts)

    {

        var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;

        <div class="alert alert-@alert.AlertStyle @dismissableClass">

            @if (alert.Dismissable)

            {

                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

            }

            @Html.Raw(alert.Message)

        </div>

    }
}

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootswatch.css" rel="stylesheet" />
    <link href="~/lib/site.css" rel="stylesheet"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" id="myNavbar">
            <div class="container-fluid">
                <a href="@Url.Action("index","home")" class="navbar-brand">
                    <!-- Logo Image -->
                    <img src="https://res.cloudinary.com/mhmd/image/upload/v1557368579/logo_iqjuay.png" width="45" alt="" class="d-inline-block align-middle mr-2">
                    <!-- Logo Text -->
                    <span class="text-uppercase font-weight-bold">E.S</span>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link active" aria-current="page" href="@Url.Action("index","home")">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("login","Account")">Anmelden</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("register","Account")">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("index","Admin")" tabindex="-1" aria-disabled="false">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("index","Member")" tabindex="-1" aria-disabled="false">Member</a>
                        </li>


                        <li class="nav-item px-4 dropdown">
                            <!-- we will put our "Services" mega menu in here -->
                            <a class="nav-link dropdown-toggle" href="#" id="servicesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Services</a>
                            <div class="dropdown-menu dropdown-menu-left" aria-labelledby="servicesDropdown">
                                <a class="dropdown-item" href="#">What we do</a>
                                <a class="dropdown-item" href="#">How we fit your needs</a>
                                <div class="dropdown-divider"></div>
                                <div class="d-md-flex align-items-start justify-content-start">
                                    <div>
                                        <div class="dropdown-header">Development</div>
                                        <a class="dropdown-item" href="#">Bespoke software</a>
                                        <a class="dropdown-item" href="#">Mobile apps</a>
                                        <a class="dropdown-item" href="#">Websites</a>
                                    </div>
                                    <div>
                                        <div class="dropdown-header">Professional Services</div>
                                        <a class="dropdown-item" href="#">Project rescue</a>
                                        <a class="dropdown-item" href="#">Source code recovery</a>
                                        <a class="dropdown-item" href="#">Application support &amp; maintenance</a>
                                    </div>
                                    <div>
                                        <div class="dropdown-header">Fixed Price Services</div>
                                        <a class="dropdown-item" href="#">Add cookie consent</a>
                                        <a class="dropdown-item" href="#">Add captcha</a>
                                        <a class="dropdown-item" href="#">Add core data</a>
                                        <a class="dropdown-item" href="#">Custom error pages</a>
                                        <a class="dropdown-item" href="#">Contact form creation</a>
                                        <a class="dropdown-item" href="#">Automated backups</a>
                                        <a class="dropdown-item" href="#">Image to HTML</a>
                                    </div>
                                </div>
                            </div>
                        </li>



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        @if (TempData["message"] != null)
        {

            <div class="alert alert-info" style="text-align:center;">

                <strong>@TempData["message"]</strong>
            </div>
        }
        @RenderBody()
    </div>

    @*<div class="container body-content">
            @{ Html.RenderPartial("_Alerts"); }
            <partial name="_Alerts.cshtml">

                @RenderBody()
        </div>*@
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
</body>
</html>